/**
 * Declarative customer setup step definitions — data only.
 */

import {
  SetupStepCategories,
  SetupStepKeys,
  type SetupStepDefinition,
  type SetupStepKey,
} from "@/lib/customer-setup/types";

export const SETUP_STEP_DEFINITIONS: readonly SetupStepDefinition[] = [
  {
    key: SetupStepKeys.BUSINESS_INFO,
    category: SetupStepCategories.FOUNDATION,
    title: "Business information",
    description: "Name, industry, and where you serve customers.",
    whyItMatters: "I use this to speak accurately about your business.",
    required: true,
    canSkip: false,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: true,
    destinationRoute: "/dashboard/setup/business",
    primaryActionLabel: "Update business info",
    estimatedEffort: "About 2 minutes",
    helpText: "Add your business name at minimum. Industry and location help local marketing.",
    dependencyKeys: [],
    sortOrder: 10,
  },
  {
    key: SetupStepKeys.WEBSITE,
    category: SetupStepCategories.FOUNDATION,
    title: "Website",
    description: "Your website URL, or confirm you do not have one.",
    whyItMatters: "A website helps me learn your services and messaging — but it is optional.",
    required: false,
    canSkip: true,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: false,
    destinationRoute: "/dashboard/website-analysis",
    primaryActionLabel: "Review website setup",
    estimatedEffort: "About 1 minute",
    helpText: "You can skip this if you do not have a website. Other setup can continue.",
    dependencyKeys: [],
    sortOrder: 20,
  },
  {
    key: SetupStepKeys.MARKETING_GOALS,
    category: SetupStepCategories.FOUNDATION,
    title: "Marketing goals",
    description: "What success looks like for your marketing.",
    whyItMatters: "Goals keep my recommendations focused on what matters to you.",
    required: true,
    canSkip: false,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: true,
    destinationRoute: "/dashboard/setup/goals",
    primaryActionLabel: "Set marketing goals",
    estimatedEffort: "About 1 minute",
    helpText: "Pick at least one goal such as more calls, reviews, or Google visibility.",
    dependencyKeys: [SetupStepKeys.BUSINESS_INFO],
    sortOrder: 30,
  },
  {
    key: SetupStepKeys.BRAND_VOICE,
    category: SetupStepCategories.FOUNDATION,
    title: "Brand voice",
    description: "How I should sound when writing for you.",
    whyItMatters: "Voice guidance keeps drafts on-brand before you approve them.",
    required: false,
    canSkip: true,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: true,
    destinationRoute: "/dashboard/brand-voice",
    primaryActionLabel: "Set brand voice",
    estimatedEffort: "About 3 minutes",
    helpText: "Recommended before content generation. You can refine it later.",
    dependencyKeys: [SetupStepKeys.BUSINESS_INFO],
    sortOrder: 40,
  },
  {
    key: SetupStepKeys.GOOGLE_BUSINESS,
    category: SetupStepCategories.CONNECTIONS,
    title: "Google Business Profile",
    description: "Connect Google so I can help with posts, reviews, and local visibility.",
    whyItMatters: "Unlocks local posts, reviews, and performance insights when you are ready.",
    required: false,
    canSkip: true,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: false,
    destinationRoute: "/dashboard/google-business-profile/connect",
    primaryActionLabel: "Connect Google",
    estimatedEffort: "About 3 minutes",
    helpText: "Optional. You can use Head of Marketing without Google, but local features stay limited.",
    dependencyKeys: [SetupStepKeys.BUSINESS_INFO],
    sortOrder: 50,
  },
  {
    key: SetupStepKeys.NOTIFICATIONS,
    category: SetupStepCategories.CONNECTIONS,
    title: "Notifications",
    description: "How you prefer to hear about approvals and important updates.",
    whyItMatters: "Keeps important work from getting buried.",
    required: false,
    canSkip: true,
    educationalOnly: true,
    adminOnly: false,
    affectsReadiness: false,
    destinationRoute: "/dashboard/notifications",
    primaryActionLabel: "Review notifications",
    estimatedEffort: "About 1 minute",
    helpText: "Optional for now. Defaults stay conservative until you change them.",
    dependencyKeys: [],
    sortOrder: 60,
  },
  {
    key: SetupStepKeys.AI_MARKETING_PROFILE,
    category: SetupStepCategories.STRATEGY,
    title: "Marketing profile",
    description: "A reusable summary of your business for content and planning.",
    whyItMatters: "Your marketing profile feeds the plan and content drafts.",
    required: false,
    canSkip: true,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: true,
    destinationRoute: "/dashboard/ai-profile",
    primaryActionLabel: "Open marketing profile",
    estimatedEffort: "About 2 minutes",
    helpText: "Usually created after business basics. You can refresh it later.",
    dependencyKeys: [SetupStepKeys.BUSINESS_INFO],
    sortOrder: 70,
  },
  {
    key: SetupStepKeys.MARKETING_PLAN,
    category: SetupStepCategories.STRATEGY,
    title: "Marketing plan",
    description: "This month’s planned themes and focus.",
    whyItMatters: "Gives Head of Marketing a concrete month to work from.",
    required: false,
    canSkip: true,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: true,
    destinationRoute: "/dashboard/marketing-plan",
    primaryActionLabel: "Open marketing plan",
    estimatedEffort: "About 2 minutes",
    helpText: "Recommended once your profile basics are in place.",
    dependencyKeys: [SetupStepKeys.BUSINESS_INFO],
    sortOrder: 80,
  },
  {
    key: SetupStepKeys.HEAD_OF_MARKETING,
    category: SetupStepCategories.STRATEGY,
    title: "Head of Marketing ready",
    description: "Enough foundation for your weekly briefing.",
    whyItMatters: "This is your main place to decide what matters next.",
    required: true,
    canSkip: false,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: true,
    destinationRoute: "/dashboard",
    primaryActionLabel: "Open Head of Marketing",
    estimatedEffort: "Ready when basics are complete",
    helpText: "Requires completed onboarding with business basics and at least one marketing goal.",
    dependencyKeys: [SetupStepKeys.BUSINESS_INFO, SetupStepKeys.MARKETING_GOALS],
    sortOrder: 90,
  },
  {
    key: SetupStepKeys.APPROVAL_EDUCATION,
    category: SetupStepCategories.EXECUTION,
    title: "How approvals work",
    description: "Understand reviewing content before anything goes live.",
    whyItMatters: "Approval is your control point — it is not automatic publishing.",
    required: false,
    canSkip: true,
    educationalOnly: true,
    adminOnly: false,
    affectsReadiness: false,
    destinationRoute: "/dashboard/approvals",
    primaryActionLabel: "Review approvals",
    estimatedEffort: "About 1 minute",
    helpText: "Acknowledge once you understand that approving is separate from publishing.",
    dependencyKeys: [],
    sortOrder: 100,
  },
  {
    key: SetupStepKeys.PUBLISHING_EDUCATION,
    category: SetupStepCategories.EXECUTION,
    title: "How publishing works",
    description: "Understand scheduled and failed publishing recovery.",
    whyItMatters: "Publishing only happens after you approve and a destination is ready.",
    required: false,
    canSkip: true,
    educationalOnly: true,
    adminOnly: false,
    affectsReadiness: false,
    destinationRoute: "/dashboard/publishing",
    primaryActionLabel: "Review publishing",
    estimatedEffort: "About 1 minute",
    helpText: "Acknowledge once you understand destinations, scheduling, and retry basics.",
    dependencyKeys: [],
    sortOrder: 110,
  },
  {
    key: SetupStepKeys.CONTENT_READY,
    category: SetupStepCategories.EXECUTION,
    title: "Content drafting readiness",
    description: "Enough profile and voice context for useful drafts.",
    whyItMatters: "Draft quality improves once basics and voice are present.",
    required: false,
    canSkip: true,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: false,
    destinationRoute: "/dashboard/content/generator",
    primaryActionLabel: "Open content tools",
    estimatedEffort: "Ready when voice or profile exists",
    helpText: "Optional. Drafts still require your approval before publishing.",
    dependencyKeys: [SetupStepKeys.BUSINESS_INFO],
    sortOrder: 120,
  },
  {
    key: SetupStepKeys.MARKETING_PREFERENCES,
    category: SetupStepCategories.OPTIONAL,
    title: "Marketing preferences",
    description: "Standing instructions such as days or topics to avoid.",
    whyItMatters: "Preferences help Marketing Memory respect your boundaries.",
    required: false,
    canSkip: true,
    educationalOnly: false,
    adminOnly: false,
    affectsReadiness: false,
    destinationRoute: "/dashboard/marketing-preferences",
    primaryActionLabel: "Open preferences",
    estimatedEffort: "About 2 minutes",
    helpText: "Optional enhancement. You can add preferences anytime.",
    dependencyKeys: [],
    sortOrder: 130,
  },
] as const;

const BY_KEY = new Map(SETUP_STEP_DEFINITIONS.map((step) => [step.key, step]));

export function getSetupStepDefinition(key: SetupStepKey): SetupStepDefinition | null {
  return BY_KEY.get(key) ?? null;
}

export function listSetupStepDefinitions(): SetupStepDefinition[] {
  return [...SETUP_STEP_DEFINITIONS].sort((a, b) => a.sortOrder - b.sortOrder);
}

export function isSetupStepKey(value: string): value is SetupStepKey {
  return Object.values(SetupStepKeys).includes(value as SetupStepKey);
}

export function isSkippableSetupStep(key: SetupStepKey): boolean {
  return getSetupStepDefinition(key)?.canSkip === true;
}
